### ISSUE TITLE
Import Errors

### ISSUE THREAD

**Issue by egfrazier** [monodokimes/pythonmon#1]
Even though the last commit comment says the filenames were changed to lower case, they still start with uppercase which is causing ImportErrors. As soon as I run main.py:

```
Traceback (most recent call last):
  File "C:/pc_projects/pythonmon/main.py", line 1, in <module>
    from logger import Logger
ImportError: No module named 'logger'
```

**Comment by egfrazier** [comment]
I'm running Python 3.5.0 and pygame 3.5 on Windows 10

**Comment by ktyldev** [comment]
I'm assuming you mean PyGame 1.9.2 for Python 3.5 - as far as I am aware PyGame doesn't have a version 3.5.

It appears that because I was developing this on a Windows system myself Git had some minor disagreements about the casing in filenames. Many commits and messing with Git later, the issue should be resolved, as the line importing `Logger` has been removed from `main.py`.
